version: '3'

services:
  web:
    container_name: docker-node-mongo
    restart: always
    build: ./backend
    ports:
      - '9090:9090'
    external_links:
      - mongo

  mongo:
    container_name: mongo
    restart: always
    image: mongo
    # volumes:
    #   - ./data:/data/db
    ports:
      - '27017:27017'
