version: '3.7'
# volumes:
# mongodb_volume:

services:
  web:
    container_name: docker-node
    image: docker-node
    restart: always
    build: ./backend
    ports:
      - '9090:9090'
    # links:
    #   - mongo
    external_links:
      - mongo
    networks:
      - node-network

  mongo:
    container_name: mongo
    restart: always
    image: mongo
    # volumes:
    #   - ./data:/data/db
    ports:
      - '27017:27017'
    # volumes:
    #   - mongodb_volume:/data/db
    networks:
      - node-network

networks:
  node-network:
    name: node-network
